-- EXPENSE TRACKER

CREATE TABLE expenses (
	id INT AUTO_INCREMENT PRIMARY KEY,
	amount DECIMAL(10,2) NOT NULL,
	category VARCHAR(100) NOT NULL,
	date DATE NOT NULL,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


SELECT * FROM expenses;